version: "1"

services:
     # PostgreSQL Database
     postgres:
          image: postgres:latest
          environment:
               POSTGRES_USER: root
               POSTGRES_PASSWORD: rootpass
               POSTGRES_DB: item
          ports:
               - "5433:5432"

     # Redis Server
     redis:
          image: "redis:latest"
          ports:
               - "6378:6379"
